#include<stdio.h>
#include<stdlib.h>
intbinsearch(intarray[],intval,intlo,inthi);
intmain()
{intlen,i=0,val,key;
intarray[30];
printf("masukannilai\n");
printf("\ntekan<0untukberhenti>");

scanf("%d",&array[i]);
while(array[i]!=0)
{i++;
printf("\ntekan<0untukberhenti>");
scanf("%d",&array[i]);
}
len=i;//lengthistakenasiandnotasi+1as0isalsostoredinthearray
printf("\n****Array****\n");
for(i=0;i<len;i++)
printf("%d\t",array[i]);
printf("\n\nMasukannilaiyangakandicari:");
scanf("%d",&val);
key=binsearch(array,val,0,len-1);
//callthefunctionbinsearchwhichwillserachtheelement
if(key==-1)
printf("\nAngkatidakadadalamarray");
else
printf("\nAngka%dditemukanpadaposisike%ddalamarray\n",val,key);
}
intbinsearch(intarray[],intval,intlo,inthi)
{intmid,key;
if(lo>hi)
key=-1;
else
{mid=(lo+hi)/2;
if(val==array[mid])
key=mid;

else
if(val<array[mid])
{hi=mid-1;
key=binsearch(array,val,lo,hi);
}
else
if(val>array[mid])
{lo=mid+1;
key=binsearch(array,val,lo,hi);
}
}
return(key);
}
